server:
  port: 8661

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instace.hostname}:${server.port}/eureka/
