server:
  port: 8662
spring:
  application:
    name: zuulproxy
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    demospringcloudfeignclient:
      path: /feignclient/**
      serviceId: feignclient
      stripPrefix: true
    demospringcloudeurekaclient:
      path: /eurekaclient/**
      serviceId: eurekaclient
      stripPrefix: true